name: Auto publish

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  package-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files
        run: | 
          mkdir -p dist/output/apps
          cp -r apps/* dist/output/apps/
          mkdir -p dist/output/usb-loader
          cp -r usb-loader/* dist/output/usb-loader/

      - name: Upload files
        uses: actions/upload-artifact@v3
        with: 
          name: Configurable-USB-Loader-Mod
          path: dist/output/
